import { Eye, EyeOff, LogIn, Sparkles } from 'lucide-react';
import { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { getErrorMessage } from '../../services/api';
import PageTransition from '../../components/common/PageTransition';
export default function Login(){
 const {login}=useAuth();const nav=useNavigate();const loc=useLocation();const [show,setShow]=useState(false);const [form,setForm]=useState({email:'',password:''});const [status,setStatus]=useState({busy:false,msg:''});
 const submit=async(e)=>{e.preventDefault();setStatus({busy:true,msg:''});try{const data=await login(form);nav(data.user.role==='admin'?'/admin':(loc.state?.from||'/dashboard'));}catch(err){setStatus({busy:false,msg:getErrorMessage(err)});}};
 return <PageTransition><section className="auth-page"><div className="auth-visual"><div className="auth-orb"/><span className="eyebrow"><Sparkles/> FAN HUB PLUS</span><h1>Your fandoms are waiting.</h1><p>Sign in to unlock personalized recommendations, bookmarks, notes, community submissions and your dashboard.</p></div><form className="auth-card" onSubmit={submit}><h2>Welcome back</h2><p>Enter your Fan Hub Plus account details.</p><label>Email<input type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})} required placeholder="you@example.com"/></label><label>Password<div className="password-field"><input type={show?'text':'password'} value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})} required placeholder="••••••••"/><button type="button" onClick={()=>setShow(!show)} aria-label="Toggle password visibility">{show?<EyeOff/>:<Eye/>}</button></div></label><div className="form-row-between"><label className="check-filter"><input type="checkbox"/> Remember me</label><Link to="/forgot-password">Forgot password?</Link></div>{status.msg&&<div className="form-alert error">{status.msg}</div>}<button className="button primary full" disabled={status.busy}><LogIn size={17}/>{status.busy?'Signing in…':'Sign in'}</button><p className="auth-switch">New to Fan Hub Plus? <Link to="/register">Create account</Link></p></form></section></PageTransition>;
}
