import { Bug, HelpCircle, Lightbulb, Send } from 'lucide-react';
import { useState } from 'react';
import api, { getErrorMessage } from '../services/api';
import PageTransition from '../components/common/PageTransition';
import Breadcrumbs from '../components/common/Breadcrumbs';
import { useAuth } from '../context/AuthContext';
export default function Feedback(){
 const {user}=useAuth();const [form,setForm]=useState({name:user?.name||'',email:user?.email||'',type:'suggestion',subject:'',message:''});const [status,setStatus]=useState({busy:false,msg:'',ok:false});
 const change=(e)=>setForm({...form,[e.target.name]:e.target.value});const submit=async(e)=>{e.preventDefault();setStatus({busy:true,msg:'',ok:false});try{const {data}=await api.post('/feedback',form);setStatus({busy:false,msg:data.message,ok:true});setForm({...form,subject:'',message:''});}catch(err){setStatus({busy:false,msg:getErrorMessage(err),ok:false});}};
 return <PageTransition><div className="page-hero compact"><div className="container"><Breadcrumbs items={[{label:'Feedback'}]}/><span className="eyebrow">FEEDBACK & SUPPORT</span><h1>Help us make the universe better.</h1><p>Report a bug, share a suggestion or ask a platform question. Every submission is stored for admin review.</p></div></div><section className="section container feedback-layout"><div className="feedback-cards"><article><Bug/><h3>Bug</h3><p>Something broken, confusing or behaving unexpectedly?</p></article><article><Lightbulb/><h3>Suggestion</h3><p>Share an idea that could improve the fandom experience.</p></article><article><HelpCircle/><h3>Query</h3><p>Ask a question about features, navigation or platform content.</p></article></div><form className="form-card" onSubmit={submit}><div className="form-grid two"><label>Name<input name="name" value={form.name} onChange={change} required/></label><label>Email<input type="email" name="email" value={form.email} onChange={change} required/></label></div><div className="form-grid two"><label>Type<select name="type" value={form.type} onChange={change}><option value="bug">Bug</option><option value="suggestion">Suggestion</option><option value="query">Query</option></select></label><label>Subject<input name="subject" value={form.subject} onChange={change} placeholder="Short summary"/></label></div><label>Message<textarea name="message" rows="7" value={form.message} onChange={change} required maxLength={2000} placeholder="Tell us what happened or what you would like to see…"/></label>{status.msg&&<div className={`form-alert ${status.ok?'success':'error'}`}>{status.msg}</div>}<button className="button primary" disabled={status.busy}><Send size={17}/>{status.busy?'Sending…':'Send feedback'}</button></form></section></PageTransition>;
}
