import { Save, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useUi } from '../../context/UiContext';
import { getErrorMessage } from '../../services/api';
import PageTransition from '../../components/common/PageTransition';
import Breadcrumbs from '../../components/common/Breadcrumbs';
const fandoms=['Anime','Gaming','Movies','TV Shows','K-Pop','Comics','Manga','Cosplay'];
export default function Profile(){
 const {user,updateProfile}=useAuth();const {theme,fontSize,reducedMotion,setTheme,setFontSize,setReducedMotion}=useUi();const[form,setForm]=useState({name:'',avatar:'',bio:'',favoriteFandoms:[],categoriesOfInterest:[]});const[state,setState]=useState({busy:false,msg:'',ok:false});
 useEffect(()=>{if(user)setForm({name:user.name||'',avatar:user.avatar||'',bio:user.bio||'',favoriteFandoms:user.favoriteFandoms||[],categoriesOfInterest:user.categoriesOfInterest||[]});},[user]);
 const toggle=(key,f)=>setForm({...form,[key]:form[key].includes(f)?form[key].filter(x=>x!==f):[...form[key],f]});
 const submit=async(e)=>{e.preventDefault();setState({busy:true,msg:'',ok:false});try{await updateProfile({...form,displayPreferences:{theme,fontSize,reducedMotion}});setState({busy:false,msg:'Profile updated successfully.',ok:true});}catch(err){setState({busy:false,msg:getErrorMessage(err),ok:false});}};
 return <PageTransition><div className="page-hero compact"><div className="container"><Breadcrumbs items={[{label:'Profile'}]}/><span className="eyebrow">YOUR PROFILE</span><h1>Make Fan Hub Plus yours.</h1><p>Update your identity, favorite fandoms and display preferences.</p></div></div><section className="section container profile-layout"><aside className="profile-preview"><img src={form.avatar||user?.avatar} alt=""/><h2>{form.name||user?.name}</h2><p>{user?.email}</p><span className="status-badge approved">{user?.role}</span></aside><form className="form-card" onSubmit={submit}><div className="form-grid two"><label>Name<input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} required/></label><label>Avatar URL<input value={form.avatar} onChange={(e)=>setForm({...form,avatar:e.target.value})} placeholder="https://…"/></label></div><label>Bio<textarea rows="4" maxLength="300" value={form.bio} onChange={(e)=>setForm({...form,bio:e.target.value})}/></label><fieldset><legend>Favorite fandoms</legend><div className="choice-grid">{fandoms.map(f=><button type="button" className={form.favoriteFandoms.includes(f)?'active':''} onClick={()=>toggle('favoriteFandoms',f)} key={f}>{f}</button>)}</div></fieldset><fieldset><legend>Categories of interest</legend><div className="choice-grid">{fandoms.map(f=><button type="button" className={form.categoriesOfInterest.includes(f)?'active':''} onClick={()=>toggle('categoriesOfInterest',f)} key={f}>{f}</button>)}</div></fieldset><fieldset><legend>Display preferences</legend><div className="form-grid three"><label>Theme<select value={theme} onChange={(e)=>setTheme(e.target.value)}><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Font size<select value={fontSize} onChange={(e)=>setFontSize(e.target.value)}><option value="small">Small</option><option value="medium">Medium</option><option value="large">Large</option></select></label><label className="check-filter profile-check"><input type="checkbox" checked={reducedMotion} onChange={(e)=>setReducedMotion(e.target.checked)}/> Reduce motion</label></div></fieldset>{state.msg&&<div className={`form-alert ${state.ok?'success':'error'}`}>{state.msg}</div>}<button className="button primary" disabled={state.busy}><Save size={17}/>{state.busy?'Saving…':'Save profile'}</button></form></section></PageTransition>;
}
