import { Send, ShieldCheck } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api, { getErrorMessage } from '../../services/api';
import PageTransition from '../../components/common/PageTransition';
import Breadcrumbs from '../../components/common/Breadcrumbs';
export default function SubmitContent(){
 const[cats,setCats]=useState([]);const[form,setForm]=useState({title:'',category:'',fandom:'Anime',submissionType:'fan_article',summary:'',content:'',mediaUrls:''});const[state,setState]=useState({busy:false,msg:'',ok:false});
 useEffect(()=>{api.get('/categories').then(({data})=>{setCats(data.data||[]);if(data.data?.[0])setForm(f=>({...f,category:f.category||data.data[0]._id,fandom:f.fandom||data.data[0].name}))});},[]);
 const change=(e)=>setForm({...form,[e.target.name]:e.target.value});const submit=async(e)=>{e.preventDefault();setState({busy:true,msg:'',ok:false});try{const payload={...form,mediaUrls:form.mediaUrls.split(',').map(x=>x.trim()).filter(Boolean)};const{data}=await api.post('/submissions',payload);setState({busy:false,msg:data.message,ok:true});setForm({...form,title:'',summary:'',content:'',mediaUrls:''});}catch(err){setState({busy:false,msg:getErrorMessage(err),ok:false});}};
 return <PageTransition><div className="page-hero compact"><div className="container"><Breadcrumbs items={[{label:'Submissions',to:'/submissions'},{label:'Submit content'}]}/><span className="eyebrow">FAN CREATOR PORTAL</span><h1>Share something the community will love.</h1><p>Every submission goes through admin approval before it can appear publicly.</p><span className="notice-pill"><ShieldCheck/> Moderated before publication</span></div></div><section className="section container narrow"><form className="form-card" onSubmit={submit}><div className="form-grid two"><label>Title<input name="title" value={form.title} onChange={change} required/></label><label>Submission type<select name="submissionType" value={form.submissionType} onChange={change}><option value="fan_article">Fan article</option><option value="cosplay_photo">Cosplay photo</option><option value="fan_art">Fan art</option><option value="review">Review</option><option value="guide">Guide</option></select></label><label>Category<select name="category" value={form.category} onChange={(e)=>{const c=cats.find(x=>x._id===e.target.value);setForm({...form,category:e.target.value,fandom:c?.name||form.fandom})}} required>{cats.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label><label>Fandom<input name="fandom" value={form.fandom} onChange={change} required/></label></div><label>Summary<textarea name="summary" rows="3" maxLength={500} value={form.summary} onChange={change} required/></label><label>Full content<textarea name="content" rows="10" value={form.content} onChange={change} required/></label><label>Media URLs <small>(optional, comma-separated)</small><input name="mediaUrls" value={form.mediaUrls} onChange={change} placeholder="https://… , https://…"/></label>{state.msg&&<div className={`form-alert ${state.ok?'success':'error'}`}>{state.msg}{state.ok&&<> <Link to="/submissions">Track submission</Link></>}</div>}<button className="button primary" disabled={state.busy}><Send size={17}/>{state.busy?'Submitting…':'Submit for review'}</button></form></section></PageTransition>;
}
