import { Edit3, Plus, Search, Trash2, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import api, { getErrorMessage } from '../../services/api';
import EmptyState from '../../components/common/EmptyState';

const configs = {
 categories:{title:'Categories',endpoint:'/categories',search:false,columns:[['name','Name'],['slug','Slug'],['tagline','Tagline'],['active','Active']],fields:[['name','Name','text',true],['slug','Slug','text',true],['tagline','Tagline'],['description','Description','textarea',true],['icon','Icon name'],['color','Accent color','color'],['bannerImage','Banner image URL','text',true],['displayOrder','Display order','number'],['active','Active','boolean']]},
 content:{title:'Content',endpoint:'/content',columns:[['title','Title'],['fandom','Fandom'],['type','Type'],['popularityScore','Popularity']],fields:[['title','Title','text',true],['slug','Slug'],['category','Category','category',true],['fandom','Fandom','text',true],['type','Type','select',true,['article','video','audio','image','profile']],['genre','Genres (comma-separated)','array'],['description','Description','textarea',true],['fullContent','Full content','textarea'],['tags','Tags (comma-separated)','array'],['bannerUrl','Banner image URL','text',true],['thumbnailUrl','Thumbnail URL','text',true],['releaseDate','Release date','date'],['releaseYear','Release year','number'],['popularityScore','Popularity score','number'],['isFeatured','Featured','boolean'],['isTrending','Trending','boolean']]},
 media:{title:'Media',endpoint:'/media',columns:[['title','Title'],['fandom','Fandom'],['type','Type'],['viewCount','Views']],fields:[['title','Title','text',true],['type','Type','select',true,['video','trailer','audio','podcast','gallery','explainer']],['category','Category','category',true],['fandom','Fandom','text',true],['thumbnailUrl','Thumbnail URL','text',true],['mediaUrl','Media URL'],['embedUrl','Embed URL'],['audioUrl','Audio URL'],['galleryImages','Gallery URLs (comma-separated)','array'],['description','Description','textarea',true],['duration','Duration'],['artistOrCreator','Creator'],['tags','Tags','array'],['isFeatured','Featured','boolean']]},
 characters:{title:'Characters',endpoint:'/characters',columns:[['name','Name'],['fandom','Fandom'],['role','Role'],['popularityScore','Popularity']],fields:[['name','Name','text',true],['japaneseName','Alternate name'],['category','Category','category',true],['fandom','Fandom','text',true],['role','Role'],['bio','Bio','textarea',true],['backstory','Backstory','textarea'],['abilities','Abilities','array'],['voiceActor','Voice actor'],['appearances','Appearances','array'],['imageUrl','Image URL','text',true],['bannerUrl','Banner URL'],['popularityScore','Popularity score','number'],['isFeatured','Featured','boolean'],['quotes','Quotes','array']]},
 articles:{title:'Articles',endpoint:'/articles',columns:[['title','Title'],['fandom','Fandom'],['authorName','Author'],['isFeatured','Featured']],fields:[['title','Title','text',true],['slug','Slug'],['category','Category','category',true],['fandom','Fandom','text',true],['summary','Summary','textarea',true],['content','Article content','textarea',true],['authorName','Author name'],['authorRole','Author role'],['authorAvatar','Author avatar URL'],['coverImage','Cover image URL','text',true],['tags','Tags','array'],['readTime','Read time'],['isFeatured','Featured','boolean'],['publishedAt','Published date','date']]},
 merchandise:{title:'Merchandise',endpoint:'/merchandise',columns:[['name','Name'],['fandom','Fandom'],['tag','Tag'],['isUpcoming','Upcoming']],fields:[['name','Name','text',true],['category','Category','category',true],['fandom','Fandom','text',true],['description','Description','textarea',true],['imageUrl','Image URL','text',true],['galleryImages','Gallery URLs','array'],['tag','Tag','select',true,['Limited Edition','Pre-Order','Collectible','Official Merch']],['isUpcoming','Upcoming','boolean'],['releaseDate','Release text'],['manufacturer','Manufacturer'],['scaleOrSize','Scale / size'],['officialStoreUrl','Official store URL'],['popularityScore','Popularity score','number']]},
 releases:{title:'Upcoming Releases',endpoint:'/releases',columns:[['title','Title'],['fandom','Fandom'],['releaseType','Type'],['releaseDate','Release date']],fields:[['title','Title','text',true],['category','Category','category',true],['fandom','Fandom','text',true],['releaseType','Release type','select',true,['Anime','Game','Movie','TV Show','Comic','Manga','Merchandise Drop']],['releaseDate','Release date','date',true],['platform','Platform'],['description','Description','textarea',true],['bannerImage','Banner image URL','text',true],['hypeCount','Hype count','number'],['officialTrailerUrl','Trailer URL'],['isConfirmed','Confirmed','boolean']]},
 events:{title:'Events',endpoint:'/events',columns:[['title','Title'],['city','City'],['type','Type'],['startDate','Start']],fields:[['title','Title','text',true],['slug','Slug'],['category','Category','category',true],['fandom','Fandom'],['type','Type','select',true,['Convention','Cosplay Meetup','Screening','Premiere','Release Event','Tournament']],['description','Description','textarea',true],['city','City','text',true],['country','Country'],['venue','Venue','text',true],['address','Address','text',true],['lat','Latitude','number',true],['lng','Longitude','number',true],['startDate','Start date','datetime-local',true],['endDate','End date','datetime-local',true],['ticketLink','Ticket URL'],['bannerImage','Banner image URL','text',true],['attendeesCount','Attendees','number'],['isFeatured','Featured','boolean']]}
};

const blankFor=(config)=>Object.fromEntries(config.fields.map(([k])=>[k,k==='active'||k==='isConfirmed'?true:(k==='isFeatured'||k==='isTrending'||k==='isUpcoming'?false:'')]));
const display=(item,key)=>{const v=item[key];if(typeof v==='boolean')return v?'Yes':'No';if(key.toLowerCase().includes('date')&&v)return new Date(v).toLocaleDateString();if(Array.isArray(v))return v.join(', ');return v?.name||String(v??'—');};

export default function AdminCrudPage({resource}){
 const config=configs[resource];const[items,setItems]=useState([]);const[cats,setCats]=useState([]);const[query,setQuery]=useState('');const[loading,setLoading]=useState(true);const[modal,setModal]=useState(false);const[editing,setEditing]=useState(null);const[form,setForm]=useState(()=>blankFor(config));const[state,setState]=useState({busy:false,msg:''});
 const load=async()=>{setLoading(true);try{const{data}=await api.get(config.endpoint,{params:{limit:100}});setItems(data.data||[]);}finally{setLoading(false);}};
 useEffect(()=>{load();api.get('/categories').then(({data})=>setCats(data.data||[])).catch(()=>{});},[resource]);
 const filtered=useMemo(()=>items.filter(x=>!query||JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[items,query]);
 const openNew=()=>{setEditing(null);setForm(blankFor(config));setState({busy:false,msg:''});setModal(true);};
 const openEdit=(item)=>{setEditing(item);const next=blankFor(config);config.fields.forEach(([k,,type])=>{let v;if(k==='lat')v=item.coordinates?.lat??'';else if(k==='lng')v=item.coordinates?.lng??'';else v=item[k];if(type==='category')v=v?._id||v||'';else if(type==='array')v=Array.isArray(v)?v.join(', '):v||'';else if((type==='date'||type==='datetime-local')&&v){const d=new Date(v);v=type==='date'?d.toISOString().slice(0,10):new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}next[k]=v??'';});setForm(next);setState({busy:false,msg:''});setModal(true);};
 const change=(key,type,value)=>setForm(f=>({...f,[key]:type==='boolean'?Boolean(value):value}));
 const submit=async(e)=>{e.preventDefault();setState({busy:true,msg:''});try{const payload={};config.fields.forEach(([k,,type])=>{let v=form[k];if(type==='array')v=String(v||'').split(',').map(s=>s.trim()).filter(Boolean);if(type==='number'&&v!=='')v=Number(v);if(type==='boolean')v=Boolean(v);if(k!=='lat'&&k!=='lng'&&v!=='')payload[k]=v;});if(resource==='events')payload.coordinates={lat:Number(form.lat),lng:Number(form.lng)};if(editing)await api.put(`${config.endpoint}/${editing._id}`,payload);else await api.post(config.endpoint,payload);setModal(false);await load();}catch(err){setState({busy:false,msg:getErrorMessage(err)});}};
 const remove=async(item)=>{if(!window.confirm(`Delete “${item.title||item.name}”?`))return;await api.delete(`${config.endpoint}/${item._id}`);load();};
 return <div><div className="admin-page-head"><div><span className="eyebrow">CRUD MANAGEMENT</span><h1>{config.title}</h1><p>Add, edit, remove and review database-backed {config.title.toLowerCase()}.</p></div><button className="button primary" onClick={openNew}><Plus size={17}/>Add new</button></div><div className="admin-toolbar"><label className="search-field"><Search size={17}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={`Search ${config.title.toLowerCase()}…`}/></label><span>{filtered.length} records</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr>{config.columns.map(([,label])=><th key={label}>{label}</th>)}<th>Actions</th></tr></thead><tbody>{filtered.map(item=><tr key={item._id}>{config.columns.map(([key])=><td key={key}>{display(item,key)}</td>)}<td><div className="table-actions"><button onClick={()=>openEdit(item)} aria-label="Edit"><Edit3 size={16}/></button><button className="danger-icon" onClick={()=>remove(item)} aria-label="Delete"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table>{!loading&&!filtered.length&&<EmptyState title="No records found"/>}</div>{modal&&<div className="modal-backdrop"><form className="crud-modal" onSubmit={submit}><header><div><span className="eyebrow">{editing?'EDIT RECORD':'NEW RECORD'}</span><h2>{editing?`Edit ${editing.title||editing.name}`:`Add ${config.title}`}</h2></div><button type="button" className="modal-close static" onClick={()=>setModal(false)}><X/></button></header><div className="crud-form-grid">{config.fields.map(([key,label,type='text',required,options])=><label key={key} className={type==='textarea'?'span-two':''}>{label}{type==='textarea'?<textarea rows="4" value={form[key]??''} required={required} onChange={(e)=>change(key,type,e.target.value)}/>:type==='select'?<select value={form[key]??''} required={required} onChange={(e)=>change(key,type,e.target.value)}><option value="">Select…</option>{options.map(o=><option key={o}>{o}</option>)}</select>:type==='category'?<select value={form[key]??''} required={required} onChange={(e)=>change(key,type,e.target.value)}><option value="">Select category…</option>{cats.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select>:type==='boolean'?<input type="checkbox" checked={Boolean(form[key])} onChange={(e)=>change(key,type,e.target.checked)}/>:<input type={type} step={type==='number'?'any':undefined} value={form[key]??''} required={required} onChange={(e)=>change(key,type,e.target.value)}/>}</label>)}</div>{state.msg&&<div className="form-alert error">{state.msg}</div>}<footer><button type="button" className="button ghost" onClick={()=>setModal(false)}>Cancel</button><button className="button primary" disabled={state.busy}>{state.busy?'Saving…':editing?'Save changes':'Create record'}</button></footer></form></div>}</div>;
}
